#!/usr/bin/env bash
set -euo pipefail

export DISPLAY=:1
export WORKSPACE_REF="${EVEN_CODEX_WORKSPACE_REF:-simulator}"
export EVEN_CODEX_WORKSPACE_PATH="${EVEN_CODEX_WORKSPACE_PATH:-/opt/even-codex}"
export EVEN_CODEX_REAL_CODEX_BIN="${EVEN_CODEX_REAL_CODEX_BIN:-/opt/codex-cli/bin/codex}"
export EVEN_CODEX_RUNTIME_USER="${EVEN_CODEX_RUNTIME_USER:-dashboard}"
export EVEN_CODEX_RUNTIME_HOME="${EVEN_CODEX_RUNTIME_HOME:-/home/dashboard}"
export EVEN_CODEX_RUNTIME_ROOT="${EVEN_CODEX_RUNTIME_ROOT:-${EVEN_CODEX_RUNTIME_HOME}/.developer-dashboard/state/even-codex}"

mkdir -p /tmp/even-codex-simulator "${EVEN_CODEX_RUNTIME_HOME}"

exec env \
  HOME="${EVEN_CODEX_RUNTIME_HOME}" \
  DISPLAY="${DISPLAY}" \
  WORKSPACE_REF="${WORKSPACE_REF}" \
  EVEN_CODEX_WORKSPACE_PATH="${EVEN_CODEX_WORKSPACE_PATH}" \
  EVEN_CODEX_RUNTIME_ROOT="${EVEN_CODEX_RUNTIME_ROOT}" \
  EVEN_CODEX_RUNTIME_HOME="${EVEN_CODEX_RUNTIME_HOME}" \
  EVEN_CODEX_RUNTIME_USER="${EVEN_CODEX_RUNTIME_USER}" \
  EVEN_CODEX_REAL_CODEX_BIN="${EVEN_CODEX_REAL_CODEX_BIN}" \
  EVEN_CODEX_CODEX_SESSION_ID="${EVEN_CODEX_CODEX_SESSION_ID}" \
  /usr/local/bin/even-codex-simulator-runtime
